services:
  redis1:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --cluster-enabled yes --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ./data/redis1:/data

  redis2:
    image: redis:6.2-alpine
    ports:
      - "6380:6379"
    command: redis-server --cluster-enabled yes --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ./data/redis2:/data

  redis3:
    image: redis:6.2-alpine
    ports:
      - "6381:6379"
    command: redis-server --cluster-enabled yes --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ./data/redis3:/data

  redis4:
    image: redis:6.2-alpine
    ports:
      - "6382:6379"
    command: redis-server --cluster-enabled yes --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ./data/redis4:/data

  redis5:
    image: redis:6.2-alpine
    ports:
      - "6383:6379"
    command: redis-server --cluster-enabled yes --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ./data/redis5:/data

  redis6:
    image: redis:6.2-alpine
    ports:
      - "6384:6379"
    command: redis-server --cluster-enabled yes --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ./data/redis6:/data
